version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "443:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_PROTOCOL=https
      - N8N_SSL_KEY=/files/ssl/n8n.key
      - N8N_SSL_CERT=/files/ssl/n8n.crt
      - N8N_HOST=${DOMAIN}
      - WEBHOOK_URL=https://${DOMAIN}/
    volumes:
      - ./data:/home/node/.n8n
      - ./custom:/files/custom
      - ./ssl:/files/ssl
    env_file:
      - .env

  greenapi-router:
    image: techblog/greenapi-n8n-router
    container_name: greenapi-router
    volumes:
      - ./greenapi-router/config:/app/config/
    restart: unless-stopped
    ports:
      - "3002:8000"
